# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              TheTensor.Space
name:               TheTensor.Space
description:        Tools to Tame the Tensor
meta_description:   "Tools to Tame the Tensor"
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /articles/:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://thetensor-space.github.io"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               "favicon.png"

navbar:
    sticky:         true
    search:         true
  
# Default author settings
james:
  name:           James B. Wilson
  display_name:   James
  avatar:         images/avatar_james_b_wilson.jpg
  email:          James.Wilson@ColoState.Edu
  web:            https://www.math.colostate.edu/~jwilson/
  twitter:
  description:    "Co-Author of TheTensor.Space"

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
# Note: avatar image directories start with "/uploads/"
authors:
  pete:
    name:           Peter A. Brooksbank
    display_name:   Pete
    avatar:         images/avatar_peter_a_brooksbank.jpg
    email:
    web: 
    twitter:
    description:    "Co-Author of TheTensor.Space"
  
  josh:
    name:           Joshua F. Maglione
    display_name:   Josh
    avatar:         images/avatar_joshua_maglione.jpg
    email:
    web: 
    twitter:
    description:    "Co-Author of TheTensor.Space"
  james:
    name:           James B. Wilson
    display_name:   James
    avatar:         images/avatar_james_b_wilson.jpg
    email:          James.Wilson@ColoState.Edu
    web:            https://www.math.colostate.edu/~jwilson/
    twitter:
    description:    "Co-Author of TheTensor.Space"

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      
    linkedin:
    pinterest:
    twitter:        
    vimeo:          
    youtube:

# Share button
share:
    post:           false # Display share buttons on a post page
    doc:            false # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Theme implemented by <a href="https://alex-cannon.github.io/portfolio/" rel="noreferer noopener">Alexander Cannon</a> and created by <a href="https://ivanchromjak.com/" rel="noreferer noopener">human</a> Ivan Chromjak.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           12

# Blog path
paginate_path:      "/articles/:title/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

# Set permalinks and other values per collection
collections:
  events:
    output:         true
    permalink: /:collection/:title
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc


# Legacy Configuration
# Plugins
#plugins: 
#  - jekyll-paginate
#  - jekyll-archives
    
# Archives
#jekyll-archives:
#  enabled:
#    - categories
#  layout: archive
